### ISSUE TITLE
Neurolab class - New feature

### ISSUE THREAD

**Issue by tharaka27** [fossasia/neurolab-firmware#2]
Since the neurolab device can be extended not only to measure EEG but also ECG, EMG and accelerometer a separate class is needed to maintain the base class. 

<pre>NeuroLab class
   |-  ADC
   |- wifi module
   |- accelerometer 
</pre>

Hope this feature may help to decouple ADC and other modules from the main code

**Comment by bhadreshpsavani** [comment]
@tharaka27 You have implemented this feature so let's close both issues
